// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:72591161749:web:a276b3460499ae3c0c9e9c',
    messagingSenderId: '72591161749',
    projectId: 'excelerate-app-b0bb2',
    authDomain: 'excelerate-app-b0bb2.firebaseapp.com',
    storageBucket: 'excelerate-app-b0bb2.firebasestorage.app',
    measurementId: 'G-VWTR21VX3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:72591161749:android:53e431eb52734eda0c9e9c',
    messagingSenderId: '72591161749',
    projectId: 'excelerate-app-b0bb2',
    storageBucket: 'excelerate-app-b0bb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:72591161749:ios:3ba6004c64b305580c9e9c',
    messagingSenderId: '72591161749',
    projectId: 'excelerate-app-b0bb2',
    storageBucket: 'excelerate-app-b0bb2.firebasestorage.app',
    iosBundleId: 'com.example.excelerateLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:72591161749:ios:3ba6004c64b305580c9e9c',
    messagingSenderId: '72591161749',
    projectId: 'excelerate-app-b0bb2',
    storageBucket: 'excelerate-app-b0bb2.firebasestorage.app',
    iosBundleId: 'com.example.excelerateLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:72591161749:web:fda0985c63e697300c9e9c',
    messagingSenderId: '72591161749',
    projectId: 'excelerate-app-b0bb2',
    authDomain: 'excelerate-app-b0bb2.firebaseapp.com',
    storageBucket: 'excelerate-app-b0bb2.firebasestorage.app',
    measurementId: 'G-FV8GX74GYB',
  );
}
